services:
  my-core-bot:
    image: my-core-bot-go:latest
    pull_policy: never
    volumes:
      - ..:/workspace
      - ../../client_lib:/workspace/client_lib
      - replays:/workspace/replays
    working_dir: /workspace/my-core-bot/src
    entrypoint: /bin/zsh
    stdin_open: true
    tty: true
    environment:
      - GOWORK=/workspace/my-core-bot/src/go.work

  visualizer:
    image: ghcr.io/42core-team/visualizer:dev
    ports:
      - 4000:80
    volumes:
      - replays:/usr/share/nginx/html/replays

volumes:
  replays:
