services:
  my-core-bot:
    build:
      context: ../../../..
      dockerfile: .github/workflows/my-core-bot-ts-Dockerfile

    volumes:
      - ..:/workspace
      - replays:/workspace/replays
    stdin_open: true

  visualizer:
    image: ghcr.io/42core-team/visualizer:dev
    ports:
      - 4000:80
    volumes:
      - replays:/usr/share/nginx/html/replays

volumes:
  replays:
