name: 📋 Blank Issue
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Add a description
      placeholder: Type your description here...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Please don't forget to select an appropriate issue type.

  - type: markdown
    attributes:
      value: |
        Please try to give the issue an appropriate label based on the components of Core Game it likely affects.
